# configs/integrated_model_config.yaml

model:
  num_classes: 14
  vit_checkpoint: "/users/gm00051/projects/cvpr/baseline/Graph-Augmented-Vision-Transformers/scripts/checkpoints/best_model.pt"
  feature_dim: 768
  graph_hidden_dim: 256
  graph_num_heads: 8
  image_size: 1000
  patch_size: 16
  pretrained_image_size: 224  # Original pretrained model image size

data:
  train_image_dir: "/users/gm00051/ChestX-ray14/categorized_images/train"
  val_image_dir: "/users/gm00051/ChestX-ray14/categorized_images/val"
  test_image_dir: "/users/gm00051/ChestX-ray14/categorized_images/test"
  train_label_file: "/users/gm00051/ChestX-ray14/labels/train_list.txt"
  val_label_file: "/users/gm00051/ChestX-ray14/labels/val_list.txt"
  test_label_file: "/users/gm00051/ChestX-ray14/labels/test_list.txt"
  bbox_file: "/users/gm00051/ChestX-ray14/labels/BBox_List_2017.csv"

training:
  batch_size: 128
  num_workers: 8
  gradient_clip_val: 1.0
  mixed_precision: true
  accumulate_grad_batches: 4


optimizer:
  lr: 1.0e-4
  weight_decay: 0.01
  first_cycle_steps: 30
  max_lr: 3.0e-4
  min_lr: 5.0e-5
  warmup_steps: 5
  gamma: 0.5

paths:
  checkpoint_dir: "/users/gm00051/projects/cvpr/baseline+spatial/checkpoints"
  log_dir: "/users/gm00051/projects/cvpr/baseline+spatial/logs"
  output_dir: "/users/gm00051/projects/cvpr/baseline+spatial/outputs"

wandb:
  project: "Graph-Augmented ViT"
  entity: "mirzaeeghazal"
  run_name: "integrated-spatial-graph"
  tags: ["spatial-graph", "integrated-model"]

distributed:
  backend: "nccl"
  init_method: "env://"

